title: "Jasser Jasser"
description: "Personal Page"
baseurl: ""
url: "https://jjasser87.github.io"
header_pages:
  - index.md
  - CV.md
nav_links:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Projects"
    url: "https://example.com/projects"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
