title: "Jasser Jasser"
description: "Personal Page"
logo: "https://github.com/jjasser87/jjasser87.github.io/blob/main/_imgs/jj/JJ_logo.png?raw=true"
baseurl: ""
url: "https://jjasser87.github.io"
header_pages:
  - index.md
  - CV.md
nav_links:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Gallery"
    url: "/gallery/"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
