title: "Jasser Jasser"
description: "Personal Page"
baseurl: ""
url: "https://jjasser87.github.io"
header_pages:
  - index.md
  - CV.md
nav_links:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
