title: "Dr. Jasser (JJ) Jasser - Data Analytics Professor"
description: ""
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://jjasser87.github.io"  # update with your GitHub Pages URL
theme: minimal_mistakes_jekyll  # you can choose any GitHub Pages theme
